from PyQt6.QtWidgets import (
    QMainWindow, QWidget, QLabel, QPushButton, QVBoxLayout, QHBoxLayout, QGridLayout,
    QTabWidget, QTableWidget, QScrollArea, QDateEdit, QComboBox, QLineEdit, QGroupBox, QStatusBar
)


class Ui_AdminWindow:
    def setupUi(self, AdminWindow):
        AdminWindow.resize(1300, 820)
        AdminWindow.setWindowTitle('Пиццерия — Администратор')

        self.centralwidget = QWidget(AdminWindow)
        AdminWindow.setCentralWidget(self.centralwidget)
        main = QVBoxLayout(self.centralwidget)

        self.frameTop = QWidget()
        top = QHBoxLayout(self.frameTop)
        self.labelWindowTitle = QLabel('Панель администратора')
        self.labelCurrentUser = QLabel('Администратор')
        self.pushButtonLogout = QPushButton('Выйти')
        top.addWidget(self.labelWindowTitle)
        top.addStretch()
        top.addWidget(self.labelCurrentUser)
        top.addWidget(self.pushButtonLogout)
        main.addWidget(self.frameTop)

        self.tabWidgetMain = QTabWidget()
        main.addWidget(self.tabWidgetMain)

        # users
        self.tabUsers = QWidget()
        users = QVBoxLayout(self.tabUsers)
        self.frameUsersButtons = QWidget()
        user_buttons = QHBoxLayout(self.frameUsersButtons)
        self.pushButtonRefreshUsers = QPushButton('Обновить')
        self.pushButtonAddUser = QPushButton('Добавить')
        self.pushButtonEditUser = QPushButton('Редактировать')
        self.pushButtonDeleteUser = QPushButton('Удалить')
        for w in [self.pushButtonRefreshUsers, self.pushButtonAddUser, self.pushButtonEditUser, self.pushButtonDeleteUser]:
            user_buttons.addWidget(w)
        user_buttons.addStretch()
        users.addWidget(self.frameUsersButtons)
        self.tableWidgetUsers = QTableWidget(0, 6)
        self.tableWidgetUsers.setHorizontalHeaderLabels(['ID', 'Логин', 'Пароль', 'ФИО', 'Контакт', 'Роль'])
        users.addWidget(self.tableWidgetUsers)
        self.tabWidgetMain.addTab(self.tabUsers, 'Пользователи')

        # menu
        self.tabMenu = QWidget()
        menu = QVBoxLayout(self.tabMenu)
        self.frameMenuButtons = QWidget()
        menu_buttons = QHBoxLayout(self.frameMenuButtons)
        self.pushButtonRefreshMenu = QPushButton('Обновить')
        self.pushButtonAddPizza = QPushButton('Добавить')
        self.pushButtonEditPizza = QPushButton('Редактировать')
        self.pushButtonDeletePizza = QPushButton('Удалить')
        self.pushButtonOpenOffers = QPushButton('Акции')
        for w in [self.pushButtonRefreshMenu, self.pushButtonAddPizza, self.pushButtonEditPizza, self.pushButtonDeletePizza, self.pushButtonOpenOffers]:
            menu_buttons.addWidget(w)
        menu_buttons.addStretch()
        menu.addWidget(self.frameMenuButtons)
        self.scrollAreaMenu = QScrollArea()
        self.scrollAreaMenu.setWidgetResizable(True)
        self.scrollAreaWidgetContentsMenu = QWidget()
        self.scrollAreaMenu.setWidget(self.scrollAreaWidgetContentsMenu)
        menu.addWidget(self.scrollAreaMenu)
        self.tabWidgetMain.addTab(self.tabMenu, 'Меню')

        # orders
        self.tabOrders = QWidget()
        orders = QVBoxLayout(self.tabOrders)
        self.frameOrderFilters = QWidget()
        filters = QGridLayout(self.frameOrderFilters)
        self.labelDateFrom = QLabel('Дата с')
        self.dateEditFrom = QDateEdit()
        self.dateEditFrom.setCalendarPopup(True)
        self.labelDateTo = QLabel('Дата по')
        self.dateEditTo = QDateEdit()
        self.dateEditTo.setCalendarPopup(True)
        self.labelStatusFilter = QLabel('Статус')
        self.comboBoxStatusFilter = QComboBox()
        self.pushButtonApplyOrderFilters = QPushButton('Применить')
        self.pushButtonRefreshOrders = QPushButton('Обновить')
        filters.addWidget(self.labelDateFrom, 0, 0)
        filters.addWidget(self.dateEditFrom, 0, 1)
        filters.addWidget(self.labelDateTo, 0, 2)
        filters.addWidget(self.dateEditTo, 0, 3)
        filters.addWidget(self.labelStatusFilter, 0, 4)
        filters.addWidget(self.comboBoxStatusFilter, 0, 5)
        filters.addWidget(self.pushButtonApplyOrderFilters, 0, 6)
        filters.addWidget(self.pushButtonRefreshOrders, 0, 7)
        orders.addWidget(self.frameOrderFilters)
        self.tableWidgetOrders = QTableWidget(0, 8)
        self.tableWidgetOrders.setHorizontalHeaderLabels(['ID', 'Клиент', 'Дата', 'Тип', 'Адрес', 'Комментарий', 'Сумма', 'Статус'])
        orders.addWidget(self.tableWidgetOrders)
        self.frameOrderStatus = QWidget()
        order_status = QHBoxLayout(self.frameOrderStatus)
        self.labelSelectedOrder = QLabel('Выбранный заказ')
        self.lineEditSelectedOrderId = QLineEdit()
        self.labelNewStatus = QLabel('Новый статус')
        self.comboBoxNewStatus = QComboBox()
        self.pushButtonUpdateStatus = QPushButton('Изменить статус')
        order_status.addWidget(self.labelSelectedOrder)
        order_status.addWidget(self.lineEditSelectedOrderId)
        order_status.addWidget(self.labelNewStatus)
        order_status.addWidget(self.comboBoxNewStatus)
        order_status.addWidget(self.pushButtonUpdateStatus)
        orders.addWidget(self.frameOrderStatus)
        self.tabWidgetMain.addTab(self.tabOrders, 'Заказы')

        # analytics
        self.tabAnalytics = QWidget()
        analytics = QVBoxLayout(self.tabAnalytics)
        self.frameAnalyticsTop = QWidget()
        analytics_buttons = QHBoxLayout(self.frameAnalyticsTop)
        self.pushButtonRefreshAnalytics = QPushButton('Обновить')
        self.pushButtonGenerateReport = QPushButton('Сформировать отчет')
        analytics_buttons.addWidget(self.pushButtonRefreshAnalytics)
        analytics_buttons.addWidget(self.pushButtonGenerateReport)
        analytics_buttons.addStretch()
        analytics.addWidget(self.frameAnalyticsTop)

        self.groupBoxTotalSales = QGroupBox('Общая сумма заказов')
        total_layout = QVBoxLayout(self.groupBoxTotalSales)
        self.labelTotalSalesValue = QLabel('0.00 ₽')
        total_layout.addWidget(self.labelTotalSalesValue)
        analytics.addWidget(self.groupBoxTotalSales)

        self.groupBoxOrderStats = QGroupBox('Статистика по статусам')
        stats_layout = QVBoxLayout(self.groupBoxOrderStats)
        self.tableWidgetStatusStats = QTableWidget(0, 2)
        self.tableWidgetStatusStats.setHorizontalHeaderLabels(['Статус', 'Количество'])
        stats_layout.addWidget(self.tableWidgetStatusStats)
        analytics.addWidget(self.groupBoxOrderStats)

        self.groupBoxPopularPizzas = QGroupBox('Популярные позиции')
        popular_layout = QVBoxLayout(self.groupBoxPopularPizzas)
        self.tableWidgetPopularPizzas = QTableWidget(0, 3)
        self.tableWidgetPopularPizzas.setHorizontalHeaderLabels(['Позиция', 'Количество', 'Сумма'])
        popular_layout.addWidget(self.tableWidgetPopularPizzas)
        analytics.addWidget(self.groupBoxPopularPizzas)
        self.tabWidgetMain.addTab(self.tabAnalytics, 'Аналитика')

        # roles
        self.tabRoles = QWidget()
        roles = QVBoxLayout(self.tabRoles)
        self.frameRolesButtons = QWidget()
        role_buttons = QHBoxLayout(self.frameRolesButtons)
        self.pushButtonRefreshRoles = QPushButton('Обновить')
        self.pushButtonAddRole = QPushButton('Добавить')
        self.pushButtonEditRole = QPushButton('Редактировать')
        self.pushButtonDeleteRole = QPushButton('Удалить')
        for w in [self.pushButtonRefreshRoles, self.pushButtonAddRole, self.pushButtonEditRole, self.pushButtonDeleteRole]:
            role_buttons.addWidget(w)
        role_buttons.addStretch()
        roles.addWidget(self.frameRolesButtons)
        self.tableWidgetRoles = QTableWidget(0, 2)
        self.tableWidgetRoles.setHorizontalHeaderLabels(['ID', 'Название роли'])
        roles.addWidget(self.tableWidgetRoles)
        self.tabWidgetMain.addTab(self.tabRoles, 'Роли')

        self.statusbar = QStatusBar(AdminWindow)
        AdminWindow.setStatusBar(self.statusbar)
