from PyQt6.QtWidgets import (
    QMainWindow, QWidget, QLabel, QPushButton, QVBoxLayout, QHBoxLayout,
    QTabWidget, QScrollArea, QTableWidget, QComboBox, QPlainTextEdit, QStatusBar
)


class Ui_ClientWindow:
    def setupUi(self, ClientWindow):
        ClientWindow.resize(1100, 760)
        ClientWindow.setWindowTitle('Пиццерия — Клиент')

        self.centralwidget = QWidget(ClientWindow)
        ClientWindow.setCentralWidget(self.centralwidget)
        main = QVBoxLayout(self.centralwidget)

        self.frameTop = QWidget()
        top = QHBoxLayout(self.frameTop)
        self.labelWindowTitle = QLabel('Личный кабинет клиента')
        self.labelUserCaption = QLabel('Клиент:')
        self.labelCurrentUser = QLabel('Клиент')
        self.pushButtonLogout = QPushButton('Выйти')
        top.addWidget(self.labelWindowTitle)
        top.addStretch()
        top.addWidget(self.labelUserCaption)
        top.addWidget(self.labelCurrentUser)
        top.addWidget(self.pushButtonLogout)
        main.addWidget(self.frameTop)

        self.tabWidgetMain = QTabWidget()
        main.addWidget(self.tabWidgetMain)

        self.tabCatalog = QWidget()
        catalog = QVBoxLayout(self.tabCatalog)
        self.frameCatalogButtons = QWidget()
        catalog_buttons = QHBoxLayout(self.frameCatalogButtons)
        self.pushButtonRefreshMenu = QPushButton('Обновить меню')
        self.pushButtonCreateOrder = QPushButton('Создать заказ')
        self.pushButtonAddComment = QPushButton('Комментарий к заказу')
        catalog_buttons.addWidget(self.pushButtonRefreshMenu)
        catalog_buttons.addWidget(self.pushButtonCreateOrder)
        catalog_buttons.addWidget(self.pushButtonAddComment)
        catalog_buttons.addStretch()
        catalog.addWidget(self.frameCatalogButtons)
        self.scrollAreaCatalog = QScrollArea()
        self.scrollAreaCatalog.setWidgetResizable(True)
        self.scrollAreaWidgetContentsCatalog = QWidget()
        self.scrollAreaCatalog.setWidget(self.scrollAreaWidgetContentsCatalog)
        catalog.addWidget(self.scrollAreaCatalog)
        self.tabWidgetMain.addTab(self.tabCatalog, 'Меню')

        self.tabOrders = QWidget()
        orders = QVBoxLayout(self.tabOrders)
        self.frameOrdersTop = QWidget()
        orders_top = QHBoxLayout(self.frameOrdersTop)
        self.labelOrdersStatus = QLabel('Статус:')
        self.comboBoxOrderStatusFilter = QComboBox()
        self.pushButtonRefreshOrders = QPushButton('Обновить')
        self.pushButtonDeleteOrder = QPushButton('Удалить заказ')
        self.labelDeleteHint = QLabel('Удаление только для нового заказа')
        orders_top.addWidget(self.labelOrdersStatus)
        orders_top.addWidget(self.comboBoxOrderStatusFilter)
        orders_top.addWidget(self.pushButtonRefreshOrders)
        orders_top.addWidget(self.pushButtonDeleteOrder)
        orders_top.addStretch()
        orders_top.addWidget(self.labelDeleteHint)
        orders.addWidget(self.frameOrdersTop)
        self.tableWidgetOrders = QTableWidget(0, 7)
        self.tableWidgetOrders.setHorizontalHeaderLabels(['ID', 'Дата', 'Тип', 'Адрес', 'Комментарий', 'Сумма', 'Статус'])
        orders.addWidget(self.tableWidgetOrders)
        self.tabWidgetMain.addTab(self.tabOrders, 'Мои заказы')

        self.tabReviews = QWidget()
        reviews = QVBoxLayout(self.tabReviews)
        self.frameReviewActions = QWidget()
        review_buttons = QHBoxLayout(self.frameReviewActions)
        self.pushButtonNewReview = QPushButton('Оставить отзыв')
        self.pushButtonAskQuestion = QPushButton('Задать вопрос')
        self.pushButtonRefreshReviews = QPushButton('Обновить')
        review_buttons.addWidget(self.pushButtonNewReview)
        review_buttons.addWidget(self.pushButtonAskQuestion)
        review_buttons.addWidget(self.pushButtonRefreshReviews)
        review_buttons.addStretch()
        reviews.addWidget(self.frameReviewActions)
        self.tableWidgetReviews = QTableWidget(0, 4)
        self.tableWidgetReviews.setHorizontalHeaderLabels(['Пицца', 'Оценка', 'Комментаррий', 'Дата'])
        reviews.addWidget(self.tableWidgetReviews)
        self.plainTextEditQuestionPreview = QPlainTextEdit()
        reviews.addWidget(self.plainTextEditQuestionPreview)
        self.tabWidgetMain.addTab(self.tabReviews, 'Отзывы')

        self.statusbar = QStatusBar(ClientWindow)
        ClientWindow.setStatusBar(self.statusbar)
